import { test, expect } from '@playwright/test';

test('test to-do app @sanity', async ({ page }) => {
  await page.goto('https://todomvc.com/examples/react/dist/');
  await page.getByTestId('text-input').click();
  await page.getByTestId('text-input').fill('buy milk');
  await page.getByTestId('text-input').press('Enter');
  await page.getByTestId('text-input').fill('water the plants');
  await page.getByTestId('text-input').press('Enter');
  await page.getByTestId('text-input').fill('go for shopping');
  await page.locator('html').click();
  await page.locator('body').press('Enter');
  await page.getByRole('listitem').filter({ hasText: 'buy milk' }).getByTestId('todo-item-toggle').check();
  await page.getByRole('listitem').filter({ hasText: 'water the plants' }).getByTestId('todo-item-toggle').check();
  await page.getByTestId('text-input').click();
  await page.getByTestId('text-input').press('Enter');
  await page.getByRole('listitem').filter({ hasText: 'water the plants' }).getByTestId('todo-item-toggle').uncheck();
  await page.getByRole('listitem').filter({ hasText: 'water the plants' }).getByTestId('todo-item-toggle').check();
  await page.locator('body').click();
  await page.locator('html').click();
  await page.getByRole('link', { name: 'Active' }).click();
  await page.getByRole('link', { name: 'Completed' }).click();
  await page.getByRole('button', { name: 'Clear completed' }).click();
  await page.getByTestId('text-input').click();
  await page.getByTestId('text-input').fill('');
  await page.getByTestId('text-input').press('CapsLock');
  await page.getByTestId('text-input').press('CapsLock');
  await page.getByTestId('text-input').fill('test the application');
  await page.getByTestId('text-input').press('Enter');
  await page.getByTestId('text-input').fill('update resume');
  await page.getByTestId('text-input').press('Enter');
  await page.getByRole('link', { name: 'All' }).click();
  await page.getByText('test the application').click();
  await page.getByRole('listitem').filter({ hasText: 'test the application' }).getByTestId('todo-item-toggle').check();
  await page.getByRole('link', { name: 'All' }).click();
  await expect(page.getByText('go for shopping')).toBeVisible();
  await page.getByText('go for shopping').click();
  await page.getByRole('listitem').filter({ hasText: 'go for shopping' }).getByTestId('todo-item-toggle').check();
  await page.getByRole('listitem').filter({ hasText: 'update resume' }).getByTestId('todo-item-toggle').check();
  await page.getByTestId('footer').click();
  await page.getByRole('button', { name: 'Clear completed' }).click();
  await page.getByTestId('text-input').click();
});